#!/bin/bash

UPGRADES=$(checkupdates)
NUMBEROFUPGRADES=$(echo "$UPGRADES" | wc -l)

if [ $NUMBEROFUPGRADES -ne 0 ]; then
echo " "$NUMBEROFUPGRADES;
fi

case $BLOCK_BUTTON in
	1) notify-send "$UPGRADES"
esac
